WebAspCap1/Areas/Docente/Models/AdicionarProfessorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAspCap1.Areas.Docente.Models
{
    public class AdicionarProfessorViewModel
    {
        public long? InstituicaoID { get; set; }
        public long? DepartamentoID { get; set; }
        public long? CursoID { get; set; }
        public long? ProfessorID { get; set; }
    }
}

WebAspCap1/Areas/Docente/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo.Cadastros;
using Modelo.Docente;
using Newtonsoft.Json;
using WebAspCap1.Areas.Docente.Models;
using WebAspCap1.Data;
using WebAspCap1.Data.DAL.Cadastros;
using WebAspCap1.Data.DAL.Docente;

namespace WebAspCap1.Areas.Docente.Controllers
{
    [Area("Docente")]
    public class ProfessorController : Controller
    {
        private readonly IESContext _context;
        private readonly InstituicaoDAL instituicaoDAL;
        private readonly DepartamentoDAL departamentoDAL;
        private readonly CursoDAL cursoDAL;
        private readonly ProfessorDAL professorDAL;

        public ProfessorController(IESContext context)
        {
            _context = context;
            instituicaoDAL = new InstituicaoDAL(context);
            departamentoDAL = new DepartamentoDAL(context);
            cursoDAL = new CursoDAL(context);
            professorDAL = new ProfessorDAL(context);
        }

        private async Task<IActionResult> ObterVisaoProfessorPorId(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await professorDAL.ObterProfessoresPorId((long)id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        public async Task<IActionResult> Index()
        {
            return View(await professorDAL.ObterProfessoresClassificadosPorNome().ToListAsync());
        }

        public IActionResult Create()
        {
            var cursos = cursoDAL.ObterCursosClassificadosPorNome().ToList();
            cursos.Insert(0, new Curso() { CursoID = 0, Nome = "Selecione o curso" });
            ViewBag.Cursos = cursos;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Nome, CursoID")] Professor professor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await professorDAL.GravarProfessor(professor);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Não foi possível inserir os dados.");
            }
            return View(professor);
        }

        public async Task<IActionResult> Edit(long? id)
        {
            ViewResult visaoProfessor = (ViewResult)await ObterVisaoProfessorPorId(id);
            Professor professores = (Professor)visaoProfessor.Model;
            ViewBag.Cursos = new SelectList(cursoDAL.ObterCursosClassificadosPorNome(), "CursoID", "Nome", professores.CursoID);
            return visaoProfessor;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long? id, [Bind("ProfessorID, Nome, CursoID")] Professor professor)
        {
            if (id != professor.ProfessorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await professorDAL.GravarProfessor(professor);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await ProfessorExists(professor.ProfessorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Cursos = new SelectList(cursoDAL.ObterCursosClassificadosPorNome(), "CursoID", "Nome", professor.CursoID);
            return View(professor);
        }

        private async Task<bool> ProfessorExists(long? id)
        {
            return await professorDAL.ObterProfessoresPorId((long)id) != null;
        }



        public async Task<IActionResult> Details(long? id)
        {
            return await ObterVisaoProfessorPorId(id);
        }

        public async Task<IActionResult> Delete(long? id)
        {
            return await ObterVisaoProfessorPorId(id);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long? id)
        {
            var professor = await professorDAL.EliminarProfessorPorId((long)id);
            TempData["Message"] = "Professor " + professor.Nome.ToUpper() + " foi removido com sucesso!";
            return RedirectToAction(nameof(Index));
        }

        public void PrepararViewBags(List<Instituicao> instituicoes, List<Departamento> departamentos, List<Curso> cursos, List<Professor> professores)
        {
            instituicoes.Insert(0, new Instituicao() { InstituicaoID = 0, Nome = "Selecione a instituição" });
            ViewBag.Instituicoes = instituicoes;

            departamentos.Insert(0, new Departamento() { DepartamentoID = 0, Nome = "Selecione o departamento" });
            ViewBag.Departamentos = departamentos;

            cursos.Insert(0, new Curso() { CursoID = 0, Nome = "Selecione o curso" });
            ViewBag.Cursos = cursos;

            professores.Insert(0, new Professor() { ProfessorID = 0, Nome = "Selecione o professor" });
            ViewBag.Professores = professores;
        }

        [HttpGet]
        public IActionResult AdicionarProfessor()
        {
            PrepararViewBags(instituicaoDAL.ObterInstituicoesClassificadasPorNome().ToList(),
                new List<Departamento>().ToList(), new List<Curso>().ToList(), new List<Professor>().ToList());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AdicionarProfessor([Bind("InstituicaoID, DepartamentoID, CursoID, ProfessorID")] AdicionarProfessorViewModel model)
        {
            if (model.InstituicaoID == 0 || model.DepartamentoID == 0 || model.CursoID == 0 || model.ProfessorID == 0)
            {
                ModelState.AddModelError("", "É preciso selecionar todos os dados");
            } else
            {
                cursoDAL.RegistrarProfessor((long)model.CursoID, (long)model.ProfessorID);
                RegistrarProfessorNaSessao((long)model.CursoID, (long)model.ProfessorID);

                PrepararViewBags(instituicaoDAL.ObterInstituicoesClassificadasPorNome().ToList(),
                    departamentoDAL.ObterDepartamentosPorInstituicao((long)model.InstituicaoID).ToList(),
                    cursoDAL.ObterCursosPorDepartamento((long)model.DepartamentoID).ToList(),
                    cursoDAL.ObterProfessoresForaDoCurso((long)model.CursoID).ToList());
            }
            return View(model);
        }

        public JsonResult ObterDepartamentosPorInstituicao(long actionID)
        {
            var departamentos = departamentoDAL.ObterDepartamentosPorInstituicao(actionID).ToList();
            return Json(new SelectList(departamentos, "DepartamentoID", "Nome"));
        }

        public JsonResult ObterCursosPorDepartamento(long actionID)
        {
            var cursos = cursoDAL.ObterCursosPorDepartamento(actionID).ToList();
            return Json(new SelectList(cursos, "CursoID", "Nome"));
        }

        public JsonResult ObterProfessoresForaDoCurso(long actionID)
        {
            var professores = cursoDAL.ObterProfessoresForaDoCurso(actionID).ToList();
            return Json(new SelectList(professores, "ProfessorID", "Nome"));
        }

        public void RegistrarProfessorNaSessao(long cursoID, long professorID)
        {
            var cursoProfessor = new CursoProfessor() { ProfessorID = professorID, CursoID = cursoID };
            List<CursoProfessor> cursosProfessor = new List<CursoProfessor>();
            string cursosProfessoresSession = HttpContext.Session.GetString("cursosProfessores");
            if (cursosProfessoresSession != null)
            {
                cursosProfessor = JsonConvert.DeserializeObject<List<CursoProfessor>>(cursosProfessoresSession);
            }
            cursosProfessor.Add(cursoProfessor);
            HttpContext.Session.SetString("cursosProfessores", JsonConvert.SerializeObject(cursosProfessor));
        }

        public IActionResult VerificarUltimosRegistros()
        {
            List<CursoProfessor> cursosProfessor = new List<CursoProfessor>();
            string cursosProfessoresSession = HttpContext.Session.GetString("cursosProfessores");
            if (cursosProfessoresSession != null)
            {
                cursosProfessor = JsonConvert.DeserializeObject<List<CursoProfessor>>(cursosProfessoresSession);
            }
            return View(cursosProfessor);
        }
    }
}

WebAspCap1/Areas/Docente/Views/Professor/AdicionarProfessor.cshtml
@model WebAspCap1.Areas.Docente.Models.AdicionarProfessorViewModel

@{
    Layout = "_LayoutIES";
}

<div class="card-block">
    <div class="card-header text-white bg-danger text-center h1">Registrando um professor em um curso</div>
    <div class="card-body">
        <form asp-action="AdicionarProfessor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InstituicaoID" class="control-label"></label>
                <select asp-for="InstituicaoID" class="form-control" asp-items="@(new SelectList(ViewBag.Instituicoes, "InstituicaoID", "Nome"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="DepartamentoID" class="control-label"></label>
                <select asp-for="DepartamentoID" class="form-control" asp-items="@(new SelectList(ViewBag.Departamentos, "DepartamentoID", "Nome"))" data-url="@Url.Action("ObterDepartamentosPorInstituicao", "Professor", new { area = "Docente" })"></select>
            </div>
            <div class="form-group">
                <label asp-for="CursoID" class="control-label"></label>
                <select asp-for="CursoID" class="form-control" asp-items="@(new	SelectList(@ViewBag.Cursos, "CursoID", "Nome"))" data-url="@Url.Action("ObterCursosPorDepartamento", "Professor", new { area = "Docente"})"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProfessorID" class="control-label"></label>
                <select asp-for="ProfessorID" class="form-control" asp-items="@(new	SelectList(@ViewBag.Professores, "ProfessorID", "Nome"))" data-url="@Url.Action("ObterProfessoresForaDoCurso", "Professor", new	{ area = "Docente" })"></select>
            </div>
            <div class="form-group	text-center	h3">
                <input type="submit" value="Registrar	Professor" class="btn btn-light" />
                <a asp-action="VerificarUltimosRegistros" class="btn btn-info">Verificar últimos registros</a>
            </div>
        </form>
    </div>
    <div class="card-footer	bg-dark	text-center	text-white">Informe	os dados acima e/ou clique em um dos botões de ação</div>
</div>

@section ScriptPage	{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $(document).on("change", '#InstituicaoID', function (e) {
            var instituicaoID = $(this).find(":selected").val();
            GetDadosParaDropDownList(instituicaoID, '#DepartamentoID', 'DEPARTAMENTO');
        });

        $(document).on("change", '#DepartamentoID', function (e) {
            var departamentoID = $(this).find(":selected").val();
            GetDadosParaDropDownList(departamentoID, '#CursoID', 'CURSO');
        });

        $(document).on("change", '#CursoID', function (e) {
            var cursoID = $(this).find(":selected").val();
            GetDadosParaDropDownList(cursoID, '#ProfessorID', 'PROFESSOR');
        });

        function GetDadosParaDropDownList(valorBuscar, controleAtualizar, nomeDado) {
            var optionControleAtualizar = controleAtualizar + ' option';
            if (valorBuscar.length > 0) {
                var url = $(controleAtualizar).data('url');
                $.getJSON(url, { actionID: valorBuscar }, function (dadosRecebidos) {
                    $(optionControleAtualizar).remove();
                    $(controleAtualizar).append('<option value="0">Selecione o ' + nomeDado + '</option');
                    for (i = 0; i < dadosRecebidos.length; i++) {
                        $(controleAtualizar).append('<option value = "' + dadosRecebidos[i].value + '" > ' + dadosRecebidos[i].text + '</option');
                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    debugger;
                    alert('Erro	de	conexão', 'Erro	obtendo	dados');
                });
            } else {
                $(optionControleAtualizar).remove();
                $(controleAtualizar).append('<option value=""></option');
            }
        }
        </script>
}

WebAspCap1/Areas/Docente/Views/Professor/Create.cshtml
@model Modelo.Docente.Professor

@{
    ViewData["Title"] = "Create";
    Layout = "_LayoutIES";
}

<div class="card-block">
    <div class="card-header text-white bg-danger text-center h1">Registrando um novo professor</div>
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CursoID" class="control-label"></label>
                <select asp-for="CursoID" class="form-control" asp-items="@(new SelectList(ViewBag.Cursos, "CursoID", "Nome"))"></select>
            </div>
            <div class="form-group text-center h3">
                <input type="submit" value="Registrar Professor" class="btn btn-light" />
                <a asp-action="Index" class="btn btn-info">Retornar	à	listagem	de	professores</a>
            </div>
        </form>
    </div>

    <div class="card-footer bg-dark text-center text-white">Informe os dados acima e/ou clique em um dos botões de ação</div>
</div>

@section ScriptPage	{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAspCap1/Areas/Docente/Views/Professor/Delete.cshtml
@model Modelo.Docente.Professor

@{
    Layout = "_LayoutIES";
}
@section Styles	{
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/font-awesome.min.css"
              asp-fallback-href="~/lib/font-awesome/css/all.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
}

<div class="card-block">
    <div class="card-header	text-white	bg-secondary text-center h1">Exibindo um Curso existente</div>

    @{ await Html.RenderPartialAsync("~/Areas/Docente/Views/Professor/_PartialDetailsContentCard.cshtml", Model);}

    <div class="card-footer	bg-info	text-center	text-white">
        <a asp-action="Index" class="btn btn-danger">Retornar à listagem de Professores</a>
        <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#modalConfirmationDelete">Remover Professor</button>
    </div>
</div>

<div class="modal fade" id="modalConfirmationDelete" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModal">Remoção do Professor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Confirma a exclusão do professor @Model.Nome.ToUpper() ?</p>
            </div>
            <div class="modal-footer">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="ProfessorID" />
                    <input type="submit" value="Remover Professor" class="btn btn-primary" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section ScriptPage	{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebAspCap1/Areas/Docente/Views/Professor/Details.cshtml
@model Modelo.Docente.Professor

@{
    Layout = "_LayoutIES";
}

@section Styles	{
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/font-awesome.min.css"
              asp-fallback-href="~/lib/font-awesome/css/all.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
}

<div class="card-block">
    <div class="card-header	text-white	bg-secondary text-center h1">Exibindo um professor existente</div>

    @{ await Html.RenderPartialAsync("~/Areas/Docente/Views/Professor/_PartialDetailsContentCard.cshtml", Model);}

    <div class="card-footer	bg-info	text-center	text-white">
        <a asp-action="Edit" class="btn	btn-warning" asp-route-id="@Model.ProfessorID">Alterar</a> |
        <a asp-action="Index" class="btn btn-warning">Retornar à listagem de professores</a>
    </div>
</div>

WebAspCap1/Areas/Docente/Views/Professor/Edit.cshtml
@model Modelo.Docente.Professor

@{
    Layout = "_LayoutIES";
}

<div class="card-block">
    <div class="card-header text-white bg-secondary text-center	h1">Alterando um professor existente</div>
    <div class="card-body">
        <form asp-action="Edit">
            <input type="hidden" asp-for="ProfessorID" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CursoID" class="control-label"></label>
                <select asp-for="CursoID" class="form-control" asp-items=@ViewBag.Cursos></select>
            </div>
            <div class="form-group	text-center	h3">
                <input type="submit" value="Atualizar Curso" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-warning">Retornar à listagem de professores</a>
            </div>
        </form>
    </div>
    <div class="card-footer	bg-info	text-center	text-white">Informe	os dados acima e/ou	clique em um dos botões de ação</div>
</div>

@section ScriptPage	{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAspCap1/Areas/Docente/Views/Professor/Index.cshtml
@model IEnumerable<Modelo.Docente.Professor>

@{
    Layout = "_LayoutIES";
}

@section Styles {
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" asp-fallback-href="~/lib/datatables/css/jquery.dataTables.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute" />
    </environment>
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

<div class="card-block">
    <div class="card-header text-white bg-primary text-center h1">Professores Registrados</div>
    <div class="card-body">
        <table id="tabela_professores">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Curso.Nome)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Curso.Nome)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ProfessorID">Editar</a> |
                            <a asp-action="Details" asp-route-id="@item.ProfessorID">Detalhes</a> |
                            <a asp-action="Delete" asp-route-id="@item.ProfessorID">Deletar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer bg-success text-center">
        <a asp-action="Create" class="btn-success">Registrar um novo professor</a>
    </div>
</div>

@section ScriptPage {
    <environment include="Development">
        <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"
                asp-fallback-src="~/lib/datatables/js/jquery.dataTables.min.js">
        </script>
    </environment>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tabela_professores').DataTable({
                "order": [[1, "asc"]]
            });
        });
    </script>
}

WebAspCap1/Areas/Docente/Views/Professor/VerificarUltimosRegistros.cshtml
@model IEnumerable<Modelo.Docente.CursoProfessor>
@{
    Layout = null;
}
<!DOCTYPE	html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>VerificarUltimosRegistros</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Curso)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Professor)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CursoID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProfessorID)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p>
        <a asp-action="AdicionarProfessor">
            Voltar para Adicionar Professor
        </a>
    </p>
</body>
</html>

WebAspCap1/Areas/Docente/Views/Professor/_PartialDetailsContentCard.cshtml
@model Modelo.Docente.Professor

<div class="card-body">
    <div class="form-group">
        <label asp-for="ProfessorID" class="control-label"></label>
        <br />
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </span>
            </div>
            <input asp-for="ProfessorID" class="form-control" disabled="disabled" />
        </div>
        <label asp-for="Nome" class="control-label"></label>
        <br />
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                </span>
            </div>
            <input asp-for="Nome" class="form-control" disabled="disabled" />
        </div>
        <label asp-for="Curso.Nome" class="control-label"></label>
        <br />
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                </span>
            </div>
            <input asp-for="Curso.Nome" class="form-control" disabled="disabled" />
        </div>
    </div>
</div>